#!/bin/bash -e
i3-msg "workspace 1; append_layout /home/marco/.config/i3/terminals.json"
urxvt -name "cava" -e $SHELL -c "cava;$SHELL -i"&
urxvt -name "processes" -e $SHELL -c "echo -en '\033]0;processes\a';htop;$SHELL -i"&
urxvt -name "info" -e $SHELL -c "cd /dev/shm;echo -en '\033]0;info\a';clear && neofetch | lolcat;fortune | cowsay | lolcat;$SHELL -i"&
urxvt -name "screensaver" -e $SHELL -c "echo -en '\033]0;screensaver\a';cbonsai --life 40 --live --multiplier 5 --time 0.1 --infinite;$SHELL -i"&
